### ISSUE TITLE
Minimise need to edit backup sets for everyday tasks

### ISSUE THREAD

**Issue by Pete-Cordell** [AMWA-TV/bcp-receiver-status#3]
One thing I'm not too keen on is a client editing the backup set on a routine basis in order to satisfy everyday tasks (such as templating for bulk provisioning by removing addresses).  This potentially requires the client to have detailed knowledge of each device and I don't think that moves us sufficiently on from where we are now.

You could argue that the vendor could provide the editing tool but that requires the vendor to maintain two pieces of software which I think they would prefer to avoid.

**Comment by cristian-recoseanu** [comment]
This is not relevant to this specification.
