### ISSUE TITLE
Pete's functional review comments 2024-07-25

### ISSUE THREAD

**Issue by Pete-Cordell** [AMWA-TV/bcp-receiver-status#6]
Here's my functionality review comments (I have a few editorial / stylistic comments that can wait for another iteration):

- We should probably add a section describing how "vendor specific variants" should be handled, especially their impact on overallStatus.  Also, discuss when to extend NcReceiverMonitor or create an additional class for monitoring additional functionality (for example, what should be done for my recorder scenario and licensed receiver scenario?).

- I think support of late and lost packets methods is optional.  If so, we should say this and what is returned if they are not supported (e.g. "MethodNotImplemented")

- Add comment that the touchpoints in NcStatusMonitor's NcObject base class MUST be used to indicate the IS-04 receiver the status relates to (i.e. move comments from the Feature Set document to the BCP) and the userLabel can be used as well.

- Current wording says counters will be reset when a new set of addresses is applied (i.e. on re-activation).  Is this the desired behaviour?

- Should lost/late packets be counted or ignored in the reporting delay period?

**Comment by cristian-recoseanu** [comment]
This has been superseded by changes to the spec during activity meetings.
